### ISSUE TITLE
Authenticator.credentialBackedUp type mismatch

### ISSUE THREAD

**Issue by KubaJastrz** [alexanderson1993/remix-auth-webauthn#10]
There is a type mismatch for `Authenticator.credentialBackedUp` between code and documentation.

https://github.com/alexanderson1993/remix-auth-webauthn/blob/194cb049c31568791d792efe372a8587725ecc92/src/server.ts#L48

https://github.com/alexanderson1993/remix-auth-webauthn/blob/194cb049c31568791d792efe372a8587725ecc92/README.md?plain=1#L59-L60

**Comment by alexanderson1993** [comment]
This will be fixed in the next release.
