### ISSUE TITLE
Allow attestation type to be configured when generating registration options

### ISSUE THREAD

**Issue by bradpurchase** [alexanderson1993/remix-auth-webauthn#15]
Hi there,

First off, thanks for this library. I've implemented `remix-auth-webauthn` in my app with success and learned a ton about Webauthn and Passkeys throughout the process. 

The next step in my implementation is that I'd like to store the name of the authenticator (or at least AAGUID) server-side so that I can indicate to my users where their passkey is saved so they can manage them properly. This is represented in the "Security account settings" section of the [Passkey user journeys](https://developers.google.com/identity/passkeys/ux/user-journeys#security_section_in_the_account_settings) doc published by Google.

As far as I understand it from reading the `simplewebauthn` documentation [here](https://simplewebauthn.dev/docs/packages/server#1a-supported-attestation-formats), what I need to do here is to pass a value of `direct` to the `attestationType` when generating registration options, and then the authenticator will include an attestation statement in the response that I can use to access the info I need (i.e. AAGUID).

Sadly, it seems this library always passes a value of `none` for the attestation value, so we do not have access to the attestation statement:

https://github.com/alexanderson1993/remix-auth-webauthn/blob/194cb049c31568791d792efe372a8587725ecc92/src/browser.tsx#L105

Is it possible to allow us to configure this value? It seems like there should be a few options here as per [`AttestationConveyancePreference`](https://www.w3.org/TR/webauthn-2/#enumdef-attestationconveyancepreference), defined in `simplewebauthn` [here](https://github.com/MasterKale/SimpleWebAuthn/blob/a169def3c663cb671cdc6bc6e00a4993944a61ae/packages/types/src/dom.ts#L343).

Thanks!

**Comment by alexanderson1993** [comment]
Yeah, there's no reason it can't be configurable. I don't know when I'll get to this, but PRs are welcome. If not, I'll try to make the necessary changes before the end of the week.

**Comment by bradpurchase** [comment]
PR submitted in #16. Open to feedback, thanks again!
