### ISSUE TITLE
Expected challenge not found error as of v0.3.0

### ISSUE THREAD

**Issue by bradpurchase** [alexanderson1993/remix-auth-webauthn#17]
Hi there, as of the latest release [v0.3.0](https://github.com/alexanderson1993/remix-auth-webauthn/releases/tag/v0.3.0) login via passkey is no longer functioning as it's complaining about a missing challenge.

I have followed the updated README and I'm seeing the following error:

```
Error: Expected challenge not found. It either needs to set to the `challenge` property on the auth session, or passed as context to the authenticate function.
```

Here's my loader:

```typescript
export async function loader({ request, response }: LoaderFunctionArgs) {
  const t = await i18next.getFixedT(request)

  const user = await authenticator.isAuthenticated(request)
  const session = await sessionStorage.getSession(request.headers.get("Cookie"))

  const options = await webAuthnStrategy.generateOptions(request, user, {
    meta: { title: t("Auth.Login.title") },
  })

  session.set("challenge", options.challenge)

  response?.headers.append(
    "Set-Cookie",
    await sessionStorage.commitSession(session),
  )
  response?.headers.set("Cache-Control", "no-store")

  return options
}
```

I'm wondering if the issues are stemming from the fact I don't have the Single Fetch future flag enabled. `response` is undefined in my case, so I believe the session cookie is actually not getting updated and that's why the challenge is not found.

**Comment by alexanderson1993** [comment]
Yes, I intentionally changed the Readme to reflect Single Fetch, assuming that folks not using Single Fetch would follow the pre-Single Fetch patterns. 

In your case, you'll want to return the options using the `json` helper, and set the headers there:

```ts
  session.set("challenge", options.challenge)

  return json(options, {
    headers: {
      "Set-Cookie": await sessionStorage.commitSession(session),
      "Cache-Control": "no-store"
    }
  })
```

Let me know if that works for you.

**Comment by bradpurchase** [comment]
Yeah, that did it, thanks 🙏
