### ISSUE TITLE
Why are the `response` and `type` fields required on the form?

### ISSUE THREAD

**Issue by kentcdodds** [alexanderson1993/remix-auth-webauthn#3]

**Comment by kentcdodds** [comment]
Figured this out. It's used by `handleFormSubmit`. Kinda interesting. Is there a reason these can't be handled by `handleFormSubmit` directly instead? So I could pass the `type` to `handleFormSubmit` and it could add the `response` field automatically before submitting?

**Comment by alexanderson1993** [comment]
Should be doable, although I'd need to figure out how to put the `response` value on the form before submitting it without having a `response` field in the form already.

This is the way it's handled now:

```ts
// In the handleSubmit handler

    const target = event.currentTarget;

    target.response.value =  // Do some calculations
    target.type.value = type;
    target.submit();
```

I want to make it so the form is still in charge of submitting itself - I don't want to be firing off `fetch` requests from inside the handleSubmit function. Aside from having this add its own form element to the DOM, I'm not sure what other options there are.

**Comment by kentcdodds** [comment]
I think you could use `target.prepend`. Perhaps check that it doesn't already exist first.

**Comment by alexanderson1993** [comment]
Sure. It's worth a try. I'll get that into the next release.

**Comment by alexanderson1993** [comment]
Okay, just sorted this out in the latest commit and release (0.0.8). Also tested that all of this is working on the app that I'm using this package in, and it seems to be working still.

Let me know if you come across anything else!

**Comment by kentcdodds** [comment]
Thanks for doing all that so quickly!
