### ISSUE TITLE
Cannot read properties of undefined (reading 'value') in `handleFormSubmit` with no `value` set to submit button

### ISSUE THREAD

**Issue by Geb-algebra** [alexanderson1993/remix-auth-webauthn#7]
Hi, I found that the following error occurs when `handleFormSubmit` is executed on form submit.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at handleSubmit (handleFormSubmit.js:20:61)
```
When this error occurred, I tried to process the registration by setting `registration` as the second argument to `handleFormSubmit`. I did not have a `type` field on the form, and I did not set a value on the submit button.

Is this correct usage?

Under this situation, This error seems to occur when evaluating `target.type.value` in the following line of source code. 

https://github.com/alexanderson1993/remix-auth-webauthn/blob/main/src/handleFormSubmit.tsx#L45

Thanks for developing such a great package. This save me a lot of time to implement passkey login to my Remix Stack!

**Comment by alexanderson1993** [comment]
Thanks for submitting this issue. It should be fixed in 0.0.9.
