### ISSUE TITLE
Unhandled Promise Rejection from `handleFormSubmit` when using Prisma and Safari

### ISSUE THREAD

**Issue by spencersolberg** [alexanderson1993/remix-auth-webauthn#9]
Hi. I've been having difficulties integrating this into my app so I created a test repo to help diagnose my issues.

https://github.com/spencersolberg/remix-passkey-test

It seems to work fine when using the fake in-memory database from the README in both Arc (Chromium) and Safari. Both registration and authentication works with that setup.

When I switch to a real Prisma database, registration still works for both browsers, however I cannot get authentication to work on Safari.

I only get this error in the browser console when I click authenticate:

<img width="1118" alt="Screenshot 2024-01-29 at 3 57 24 PM" src="https://github.com/alexanderson1993/remix-auth-webauthn/assets/46253322/450e7f0c-7085-43a5-acaa-2731fe55f3f9">

**Comment by alexanderson1993** [comment]
Thanks for making a reproduction repo. Unfortunately, I was not able to reproduce this. I registered and then authenticated using Safari, and was able to log in properly in both circumstances.

I'm not sure how I can be helpful, but if you find out anything else let me know.
